FROM ruby:3.0.2-alpine

RUN adduser --disabled-password ruby_user

USER ruby_user

WORKDIR /home/ruby_user

COPY --chown=ruby_user http_server.rb ./

EXPOSE 80

ENTRYPOINT [ "ruby", "http_server.rb" ]