apiVersion: v1
kind: Service
metadata:
  labels:
    name: ruby-http-app
  name: ruby-http-app
spec:
  type: LoadBalancer
  ports:
  - name: ruby-http-app
    port: 80
    targetPort: 80
  selector:
    name: ruby-http-app